-- Global settings
vim.opt.exrc = true
vim.opt.secure = true
vim.opt.syntax = 'enable'
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.termguicolors = true
vim.wo.signcolumn = 'yes'
vim.opt.updatetime = 300
